package com.nypunya.assessment.service;

import com.nypunya.assessment.entity.*; import com.nypunya.assessment.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;

@Service public class AttemptService {
 private final QuizRepository quizzes; private final QuizAttemptRepository attempts; private final QuizQuestionRepository questions; private final QuizOptionRepository options; private final QuizAnswerRepository answers;
 public AttemptService(QuizRepository q,QuizAttemptRepository a,QuizQuestionRepository qs,QuizOptionRepository o,QuizAnswerRepository ans){quizzes=q;attempts=a;questions=qs;options=o;answers=ans;}
 @Transactional public QuizAttempt start(Long quizId,Long studentId){Quiz q=quizzes.findById(quizId).orElseThrow(()->new NoSuchElementException("Quiz not found"));if(q.getStatus()!=QuizStatus.PUBLISHED)throw new IllegalStateException("Quiz is not available");long used=attempts.countByQuizIdAndStudentId(quizId,studentId);if(q.getAttemptLimit()!=null&&used>=q.getAttemptLimit())throw new IllegalStateException("Attempt limit reached");QuizAttempt a=new QuizAttempt();a.setQuizId(quizId);a.setStudentId(studentId);a.setAttemptNumber((int)used+1);return attempts.save(a);}
 @Transactional public QuizAnswer answer(Long attemptId,Long studentId,Long questionId,Long optionId){QuizAttempt a=owned(attemptId,studentId);if(a.getStatus()!=QuizAttemptStatus.IN_PROGRESS)throw new IllegalStateException("Attempt is no longer active");Quiz q=quizzes.findById(a.getQuizId()).orElseThrow(()->new NoSuchElementException("Quiz not found"));if(q.getTimeLimitMinutes()!=null&&a.getStartedAt().plusMinutes(q.getTimeLimitMinutes()).isBefore(LocalDateTime.now())){a.setStatus(QuizAttemptStatus.EXPIRED);attempts.save(a);throw new IllegalStateException("Attempt expired");}QuizQuestion question=questions.findById(questionId).orElseThrow(()->new NoSuchElementException("Question not found"));if(!question.getQuizId().equals(a.getQuizId()))throw new IllegalArgumentException("Question does not belong to quiz");QuizOption option=options.findById(optionId).orElseThrow(()->new NoSuchElementException("Option not found"));if(!option.getQuestionId().equals(questionId))throw new IllegalArgumentException("Option does not belong to question");QuizAnswer x=answers.findByAttemptIdAndQuestionId(attemptId,questionId).orElseGet(QuizAnswer::new);x.setAttemptId(attemptId);x.setQuestionId(questionId);x.setSelectedOptionId(optionId);return answers.save(x);}
 @Transactional public QuizAttempt submit(Long attemptId,Long studentId){QuizAttempt a=owned(attemptId,studentId);if(a.getStatus()!=QuizAttemptStatus.IN_PROGRESS)throw new IllegalStateException("Attempt is no longer active");Quiz q=quizzes.findById(a.getQuizId()).orElseThrow(()->new NoSuchElementException("Quiz not found"));if(q.getTimeLimitMinutes()!=null&&a.getStartedAt().plusMinutes(q.getTimeLimitMinutes()).isBefore(LocalDateTime.now())){a.setStatus(QuizAttemptStatus.EXPIRED);a.setSubmittedAt(LocalDateTime.now());return attempts.save(a);}int score=0;for(QuizAnswer x:answers.findByAttemptId(attemptId)){QuizOption o=options.findById(x.getSelectedOptionId()).orElse(null);boolean correct=o!=null&&o.isCorrect();x.setCorrect(correct);answers.save(x);if(correct){QuizQuestion question=questions.findById(x.getQuestionId()).orElse(null);if(question!=null)score+=question.getPoints();}}a.setScore(score);a.setStatus(QuizAttemptStatus.SUBMITTED);a.setSubmittedAt(LocalDateTime.now());return attempts.save(a);}
 @Transactional(readOnly=true) public QuizAttempt get(Long id,Long studentId){return owned(id,studentId);} private QuizAttempt owned(Long id,Long studentId){return attempts.findByIdAndStudentId(id,studentId).orElseThrow(()->new NoSuchElementException("Attempt not found"));}
}
