server:
  port: ${PORT:8082}
spring:
  application:
    name: course-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nypunya_lms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
security:
  jwt:
    secret: ${JWT_SECRET:change-this-in-production-to-a-long-random-secret}
